version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "hourly"
    allow:
      - dependency-name: "google-libphonenumber"
    target-branch: "main"
    commit-message:
      prefix: "deps"
